# Generated by Django 5.1.1 on 2024-09-17 16:05

import user.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_staff', models.BooleanField(default=False, help_text='Designa se o usuário pode logar no site do admin.', verbose_name='Moderador')),
                ('is_active', models.BooleanField(default=True, help_text='Designa se a conta está ativa.', verbose_name='Ativo')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Código uuid4')),
                ('matricula', models.IntegerField(unique=True, verbose_name='Matrícula')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('nome_colaborador', models.CharField(max_length=255, verbose_name='Nome do Colaborador')),
                ('necessidade_especial', models.CharField(blank=True, choices=[('F', 'Deficiência física/motora'), ('I', 'Deficiência intelectual/mental'), ('V', 'Deficiência visual'), ('A', 'Deficiência auditiva'), ('M', 'Deficiência múltipla')], max_length=1, null=True, verbose_name='Necessidade Especial')),
                ('estado_civil', models.CharField(blank=True, choices=[('S', 'Solteiro(a)'), ('C', 'Casado(a)'), ('D', 'Divorciado(a)'), ('V', 'Viúvo(a)'), ('U', 'União estável')], max_length=1, null=True, verbose_name='Estado Civil')),
                ('numero_tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Telefone')),
                ('nacionalidade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nacionalidade')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Prefiro não informar')], max_length=1, null=True, verbose_name='Sexo')),
                ('raca', models.CharField(blank=True, choices=[('BR', 'Branca'), ('PR', 'Preta'), ('PA', 'Parda'), ('IN', 'Indígena'), ('AM', 'Amarela')], max_length=2, null=True, verbose_name='Raça')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
    ]
