# Generated by Django 5.1.1 on 2024-09-19 00:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Código uuid4')),
                ('lingua', models.CharField(choices=[('PT', 'Português'), ('EN', 'Inglês')], max_length=2, verbose_name='Linguagem')),
                ('versao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Autor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('livro', models.CharField(choices=[('GN', 'Gênesis'), ('EX', 'Êxodo'), ('LV', 'Levítico'), ('NM', 'Números'), ('DT', 'Deuteronômio'), ('JS', 'Josué'), ('JZ', 'Juízes'), ('RT', 'Rute'), ('1SM', '1 Samuel'), ('2SM', '2 Samuel'), ('1RS', '1 Reis'), ('2RS', '2 Reis'), ('1CR', '1 Crônicas'), ('2CR', '2 Crônicas'), ('ED', 'Esdras'), ('NE', 'Neemias'), ('ET', 'Ester'), ('JB', 'Jó'), ('SL', 'Salmos'), ('PV', 'Provérbios'), ('EC', 'Eclesiastes'), ('CT', 'Cânticos de Salomão'), ('IS', 'Isaías'), ('JR', 'Jeremias'), ('LM', 'Lamentações'), ('EZ', 'Ezequiel'), ('DN', 'Daniel'), ('OS', 'Oséias'), ('JL', 'Joel'), ('AM', 'Amós'), ('OB', 'Obadias'), ('JN', 'Jonas'), ('MQ', 'Miquéias'), ('NA', 'Naum'), ('HC', 'Habacuque'), ('SF', 'Sofonias'), ('AG', 'Ageu'), ('ZC', 'Zacarias'), ('ML', 'Malaquias'), ('MT', 'Mateus'), ('MC', 'Marcos'), ('LC', 'Lucas'), ('JO', 'João'), ('AT', 'Atos'), ('RM', 'Romanos'), ('1CO', '1 Coríntios'), ('2CO', '2 Coríntios'), ('GL', 'Gálatas'), ('EF', 'Efésios'), ('FP', 'Filipenses'), ('CL', 'Colossenses'), ('1TS', '1 Tessalonicenses'), ('2TS', '2 Tessalonicenses'), ('1TM', '1 Timóteo'), ('2TM', '2 Timóteo'), ('TT', 'Tito'), ('FM', 'Filemom'), ('HB', 'Hebreus'), ('TG', 'Tiago'), ('1PE', '1 Pedro'), ('2PE', '2 Pedro'), ('1JO', '1 João'), ('2JO', '2 João'), ('3JO', '3 João'), ('JD', 'Judas'), ('AP', 'Apocalipse')], max_length=3, verbose_name='Livro')),
                ('testamento', models.CharField(choices=[('V', 'Novo'), ('N', 'Velho')], max_length=1, verbose_name='Testamento')),
                ('biblia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.biblia', verbose_name='Bíblia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('autor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Autor do Capítulo')),
                ('numero', models.PositiveIntegerField(verbose_name='Número do Capítulo')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.livro', verbose_name='Livro')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Versiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('numero', models.PositiveIntegerField(verbose_name='Número do Capítulo')),
                ('versiculo', models.TextField(blank=True, null=True, verbose_name='Versículo')),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.capitulo', verbose_name='Capítulo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
